# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# METADATA
title: Vittorio Iocolano's Website
author: Vittorio Iocolano
author_short: Vittorio
tagline: Personal Website
description: Vittorio Iocolano's personal website, containing biography and portfolio
keywords: Vittorio Iocolano, Software, Game, Web, Web, Developer, Programmer, Engineer, Scotland, Stirling
position: Software Engineer
workplace: 
  name: WRLD
  url: https://www.wrld3d.com
# SOCIALS
social:
  name: Vittorio Iocolano
  email: pryderi.mail@gmail.com
  links:
    - https://twitter.com/SirPryderi
    - https://www.facebook.com/vittorioiocolano
    - https://www.linkedin.com/in/vittorio-iocolano
    - https://github.com/SirPryderi
    - https://instagram.com/SirPryderi
    - https://sirpryderi.itch.io
  handles:
    github: SirPryderi
    facebook: vittorioiocolano
    instagram: sirpryderi
    itchio: sirpryderi
    linkedin: vittorio-iocolano
    google_play: Vittorio+Iocolano
# CONFIG
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sirpryderi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/avatar.png"
webmaster_verifications:
  google: "HZhxid0szqsFDeVGP9Ehpi5Rabtxh7k-qBy5c32t26g"
google_analytics_token: "UA-19676043-2"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

collections:
  posts:
    output: true
    permalink: /blog/:title
  projects:
    output: true
    permalink: /:collection/:title
  games:
    output: true
    permalink: /:collection/:title
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
